[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip nRF5340_xxAA"

rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv8m.main-none-eabihf"

